/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.emp.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmpDetails service. Represents a row in the &quot;liferay_EmpDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.emp.test.model.impl.EmpDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.emp.test.model.impl.EmpDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmpDetails
 * @generated
 */
@ProviderType
public interface EmpDetailsModel
	extends BaseModel<EmpDetails>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp details model instance should use the {@link EmpDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this emp details.
	 *
	 * @return the primary key of this emp details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emp details.
	 *
	 * @param primaryKey the primary key of this emp details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this emp details.
	 *
	 * @return the uuid of this emp details
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this emp details.
	 *
	 * @param uuid the uuid of this emp details
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the emp ID of this emp details.
	 *
	 * @return the emp ID of this emp details
	 */
	public long getEmpId();

	/**
	 * Sets the emp ID of this emp details.
	 *
	 * @param empId the emp ID of this emp details
	 */
	public void setEmpId(long empId);

	/**
	 * Returns the group ID of this emp details.
	 *
	 * @return the group ID of this emp details
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this emp details.
	 *
	 * @param groupId the group ID of this emp details
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the emp name of this emp details.
	 *
	 * @return the emp name of this emp details
	 */
	@AutoEscape
	public String getEmpName();

	/**
	 * Sets the emp name of this emp details.
	 *
	 * @param empName the emp name of this emp details
	 */
	public void setEmpName(String empName);

	/**
	 * Returns the phone num of this emp details.
	 *
	 * @return the phone num of this emp details
	 */
	public long getPhoneNum();

	/**
	 * Sets the phone num of this emp details.
	 *
	 * @param phoneNum the phone num of this emp details
	 */
	public void setPhoneNum(long phoneNum);

	/**
	 * Returns the company ID of this emp details.
	 *
	 * @return the company ID of this emp details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this emp details.
	 *
	 * @param companyId the company ID of this emp details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this emp details.
	 *
	 * @return the user ID of this emp details
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this emp details.
	 *
	 * @param userId the user ID of this emp details
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this emp details.
	 *
	 * @return the user uuid of this emp details
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this emp details.
	 *
	 * @param userUuid the user uuid of this emp details
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this emp details.
	 *
	 * @return the user name of this emp details
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this emp details.
	 *
	 * @param userName the user name of this emp details
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this emp details.
	 *
	 * @return the create date of this emp details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this emp details.
	 *
	 * @param createDate the create date of this emp details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this emp details.
	 *
	 * @return the modified date of this emp details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this emp details.
	 *
	 * @param modifiedDate the modified date of this emp details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}